name: Automated Test
on: [push]
jobs:
  automated_test:
    name: Automated Test
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"
        - name: Produce test 1 output
          run: python find_lowest_number.py test_data/test1_input.txt test1_actual.txt
        - name: Compare expected output to actual
          run: diff test_data/test1_expected.txt test1_actual.txt
        - name: Produce test 2 output
          run: python find_lowest_number.py test_data/test2_input.txt test2_actual.txt
        - name: Compare expected output to actual
          run: diff test_data/test2_expected.txt test2_actual.txt 
        - name: Produce test 3 output
          run: python find_lowest_number.py test_data/test3_input.txt test3_actual.txt
        - name: Compare expected output to actual
          run: diff test_data/test3_expected.txt test3_actual.txt
